export default function Head() {
  return (
    <>
      <title>Free Next.js Template for Startup and SaaS</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
      <link rel="icon" href="/images/favicon.ico" />
    </>
  );
}
